BandCo2.7/path/src/BureauAndCo/SiteBundle/Form/BureauType.php
<?php

namespace BureauAndCo\SiteBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class BureauType extends AbstractType
{

    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'BureauAndCo\SiteBundle\Entity\Bureau'
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'bureauandco_sitebundle_bureau';
    }
     public function getParent()
      {
        return new SurfaceExploiteType();
      }
}

BandCo2.7/path/src/BureauAndCo/SiteBundle/Controller/DefaultController.php
<?php

namespace BureauAndCo\SiteBundle\Controller;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use BureauAndCo\SiteBundle\Entity\SurfaceExploite;
use BureauAndCo\SiteBundle\Entity\SurfaceExploiteRepository;
use BureauAndCo\SiteBundle\Entity\Bureau;
use BureauAndCo\SiteBundle\Entity\Site;
use BureauAndCo\SiteBundle\Entity\Tarif;
use BureauAndCo\SiteBundle\Form\LocationType;
use BureauAndCo\SiteBundle\Form\NouvelleSurfaceType;
use BureauAndCo\SiteBundle\Form\LocataireType;
use BureauAndCo\SiteBundle\Form\EditerSurfaceType;
use BureauAndCo\SiteBundle\Entity\Location;
use BureauAndCo\SiteBundle\Entity\Locataire;
use BureauAndCo\SiteBundle\Form\DuplicateEnfantType;
use BureauAndCo\SiteBundle\Form\LocationDomiciliationType;
use BureauAndCo\SiteBundle\Entity\SalleReunion;
use BureauAndCo\SiteBundle\Entity\Enfant;
use BureauAndCo\SiteBundle\Entity\SalleFormation;
use BureauAndCo\SiteBundle\Entity\CoWorking;
use BureauAndCo\SiteBundle\Entity\Categorie;
use BureauAndCo\SiteBundle\Form\BureauType;
use BureauAndCo\SiteBundle\Form\EnfantType;
use BureauAndCo\SiteBundle\Form\SurfaceExploiteType;
use BureauAndCo\SiteBundle\Form\SalleReunionType;
use BureauAndCo\SiteBundle\Form\SalleFormationType;
use BureauAndCo\SiteBundle\Form\CoWorkingType;
use BureauAndCo\SiteBundle\Form\SiteType;
use BureauAndCo\SiteBundle\Form\CategorieType;
use BureauAndCo\SiteBundle\Form\TarifType;
use BureauAndCo\SiteBundle\Form\NewLocationType;
use BureauAndCo\UsersBundle\Entity\Client;
use BureauAndCo\UsersBundle\Entity\Entreprise;
use BureauAndCo\UsersBundle\Entity\Reservation;
use BureauAndCo\UsersBundle\Form\ReservationType;
use BureauAndCo\UsersBundle\Form\EntrepriseType;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;

class DefaultController extends Controller
{
    /**
     * @Route("/nouveauSite", name="ns")
     * @Security("has_role('ROLE_ASSISTANT')")
     */
    public function nouveauSiteAction(Request $request)
    {
      if($this->get('security.context')->isGranted('ROLE_ADMIN')) {
        $title="Nouveau site";
        $site = new Site();
        $form =$this->createForm(new SiteType(), $site);
        if ($request->isMethod('POST') && $form->handleRequest($request)->isValid()) {
          if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($site);
            $em->flush();
            $request->getSession()
            ->getFlashBag()
            ->add('success', 'Le nouveau site a été bien ajouté');
            return $this->redirect($this->generateUrl('gestion'));
          }   
        }
        return $this->render('BureauAndCoSiteBundle:Default:nouveauSite.html.twig',array( 'form' => $form->createView()));
      }
      else{
        return new Response ("acces interdit à cette page!");
      }
    }
     /**
     * @Route("/nouvelleCat", name="nc")
     * @Security("has_role('ROLE_ASSISTANT')")
     */
     public function nouvelleCatAction(Request $request)
     {
       if($this->get('security.context')->isGranted('ROLE_ADMIN')) {
         $title="Nouvelle catégorie";
         $cat = new Categorie();
         $form =$this->createForm(new CategorieType(), $cat);

         if ($request->isMethod('POST') && $form->handleRequest($request)->isValid()) {
          if ($form->isValid()) {

            $em = $this->getDoctrine()->getManager();
            $em->persist($cat);
            $em->flush();
            $request->getSession()
            ->getFlashBag()
            ->add('success', 'La nouvelle catégorie a été enregistrée avec succés');
            return $this->redirect($this->generateUrl('mesCat'));
          }   
        }
        return $this->render('BureauAndCoSiteBundle:Default:nouvelleCat.html.twig',array( 'form' => $form->createView()));
      }
      else{
        return new Response("Accés interdit à cette page!");
      }
    } 
     /**
      * @Route("/nouvelleLocation", name="nouvelleLocation")
      * @Security("has_role('ROLE_ASSISTANT')")
      */
      public function nouvelleLocationAction(Request $request)
      {
        $title="Nouvelle location";
        $message="";
        $em = $this->getDoctrine()->getManager();
        $location = new Locataire();

        $form=$this->createForm(new NewLocationType($em), $location);
       if ('POST' == $request->getMethod()) { // Si on a posté le formulaire

         $form->bind($this->get('request'));// On récupère les données du form
         if ($form->isValid()) {
          $repository = $this
          ->getDoctrine()
          ->getManager()
          ->getRepository('BureauAndCoSiteBundle:SurfaceExploite');
          $res = $repository->findOneBy(array('num' => $location->getSurface()));
          $res->setLibre("non");

          $em = $this->getDoctrine()->getManager();
            // $location->setDateFin($dateFin);
             // $location->setDateDebut($dateDebut);
          $em->persist($location);
          $em->flush();
          $request->getSession()
          ->getFlashBag()
          ->add('success', 'La nouvelle location a été enregistrée avec succés');
          return $this->redirect($this->generateUrl('gestionClient'));
           // } 
        }
      }  

      return $this->render('BureauAndCoSiteBundle:Default:locations.html.twig',array( 'message'=>$message,'title'=>$title,'form' => $form->createView()));
    }
      /**
     * @Route("/chargerSurface/{site}",  options = { "expose" = true }, name="chargerSurface",)
     * @Security("has_role('ROLE_ASSISTANT')")
     */
      public function chargerSurfaceAction(Request $request,$site)
      {
       if($request->isXmlHttpRequest()){
        $em = $this->getDoctrine()->getManager();
        $listSurface=$em->getRepository('BureauAndCoSiteBundle:SurfaceExploite')->findBy(array('site'=>$site,'libre'=>"oui",'a_enfant'=>"non"));
        if ($listSurface){
          $surfaces=array();
          foreach ($listSurface as $surface) {
            $surfaces[]=$surface->getNum();
          }
        }
        else{
          $surfaces=null;
        }
        $response=new JsonResponse();
        return $response->setData(array('surface'=>$surfaces));
      }
      else{
       throw new \Exception('accés interdit à cette ressource!');
     }
   }
       /**
      * @Route("/location/{id}", name="location")
      * @Security("has_role('ROLE_ASSISTANT')")
      */
       public function locationAction(Request $request, SurfaceExploite $surface)
       {
        $title="Contrat de location pour :".$surface->getNum();
        $message="";
        $location = new Locataire();
        $form=$this->createForm(new LocationType($em), $location);
        $repository = $this
        ->getDoctrine()
        ->getManager()
        ->getRepository('BureauAndCoSiteBundle:Locataire');
        $res = $repository->findBy(array('surface' => $surface->getNum(),'preavis'=>'non indiqué'));
        if(count($res)>0){
          $message=" Cette surface fait l'objet d'une location dont le préavis n'est pas indiqué ";
        }
        else{
         if($surface->getAenfant()=="oui"){
          return new Response(" Cette surface est désactivée!");
        }
        else{
          
          $em = $this->getDoctrine()->getManager();
          
           if ('POST' == $request->getMethod()) { // Si on a posté le formulaire

             $form->bind($this->get('request'));// On récupère les données du form
             if ($form->isValid()) {
              $surface->setLibre("non");
              $em = $this->getDoctrine()->getManager();
              $location->setSite($surface->getSite());
              $location->setSurface($surface);
              $em->persist($location);
              $em->flush();
              $request->getSession()
              ->getFlashBag()
              ->add('success', 'La nouvelle location a été enregistrée avec succés');
              return $this->redirect($this->generateUrl('gestionClient'));
              
            }
          }  
        }
      }
      
      return $this->render('BureauAndCoSiteBundle:Default:location.html.twig',array( 'message'=>$message,'title'=>$title,'form' => $form->createView()));
    }
    
      /**
      * @Route("/reservation/{id}", name="reservation")
      * @Security("has_role('ROLE_ASSISTANT')")
      */
      public function reservationAction(Request $request, SurfaceExploite $surface)
      {
        $title="Réservation pour :".$surface->getNum();
        $message="";
        $reservation = new Reservation();
        $form=$this->createForm(new ReservationType(), $reservation);
        $repository = $this
        ->getDoctrine()
        ->getManager()
        ->getRepository('BureauAndCoSiteBundle:Locataire');
        $res = $repository->findBy(array('surface' => $surface->getNum(),'preavis'=>'non indiqué'));
        if(count($res)>0){
          $message=" Cette surface fait l'objet d'une location dont le préavis n'est pas indiqué ";
        }
        else{
         if($surface->getAenfant()=="oui"){
          return new Response(" Cette surface est désactivée!");
        }
        else{
          
          $em = $this->getDoctrine()->getManager();
          
           if ('POST' == $request->getMethod()) { // Si on a posté le formulaire
             $form->bind($this->get('request'));// On récupère les données du form
             if ($form->isValid()) {
               $surface->setLibre("réservé");
               $em = $this->getDoctrine()->getManager();
               $reservation->setSite($surface->getSite());
               $reservation->setSurface($surface);
               $em->persist($reservation);
               $em->flush();
               $request->getSession()

BandCo2.7/path/src/BureauAndCo/SiteBundle/Resources/views/Default/confirmSupprimerCat.html.twig
{% extends '::base.html.twig' %} 
{% block title %}E_Gestion NouveauSite{% endblock %}

{% block body%}
  <div class="surface">

    <div class="info">
     <div class="panel panel-danger">
       
       <div class="panel-heading"> 
             <div class="icon">
             <a href="{{path('gestion')}}" rel="nofollow">
               <img src="{{ asset('bundles/framework/images/attention.png') }}" class="img-rounded" alt="icon_bureau" width="60" height="60"></a>
              </div>
        
             <h3> Êtes-vous  sûr de vouloir supprimer cette catégorie?</h2>
             <h4>Attention!</h4>
              <p> Tous les sites, les surfaces, les location et les réservations liées à cette catégorie seront également supprimées!</p>
        </div> 
    
      <div class="panel-body" >
             <div id="bureau">
              <ul>
              <li><h4>Informations </h4></li>
              
               <li>Nom:{{cat.nom}}</li>
                <li>Les sites qui seront supprimés </li>
                <ol>{% for c in cat.sites %}

                  <li> {{c.nom}}</li>
                  {% endfor %}
                  </ol>
             
                <a class="bbtn btn-danger btn-sm"  id="supprimer" title="Supprimer" href="{{path('supprimerCat',{'id':cat.id})}}">Je veux supprimer cette surface </a>
              <a class="bbtn btn-default btn-xs" id="reserver" href="{{path('mesCat')}}">Retour </a>
                 </ul>


          </div>
      
      </div>
    </div>
</div>
</div>
 {% endblock %}
 

BandCo2.7/path/src/BureauAndCo/SiteBundle/Resources/views/Default/editerSurface.html.twig
{% extends '::base.html.twig' %} 
{% block title %}E_Gestion NouveauSite{% endblock %}

{% block body%}


 <!--  <h2> Nouveau Bureau </h2> -->
  <div class="surface"> 
<h2>{{title}}</h2>
 <div class="f">
  <p>{{message}}</p>
 <div class="f">
    {{ form_start(form, {'attr': {'class': 'form-horizontal'}}) }}
    {# Les erreurs générales du formulaire. #}
    {{ form_errors(form) }}
     <!--  FIRST INSPUT FOR THE OFFICE NUMBER -->
      <div class="form-group">
              {{ form_label(form.type, "Le type", {'label_attr': {'class': 'control-label'}}) }}
              {{ form_errors(form.type) }}
              {{ form_widget(form.type, {'attr': {'class': 'form-control'}}) }}
            </div> 
            
            <div class="form-group">

              {{ form_label(form.num, "Numéro de cette surface : ", {'label_attr': {'class': 'control-label'}}) }}
              {{ form_errors(form.num) }}
              {{ form_widget(form.num, {'attr': {'class': 'form-control'}}) }}
            </div>
             <div class="form-group">

              {{ form_label(form.description, "Déscription : ", {'label_attr': {'class': 'control-label'}}) }}
              {{ form_errors(form.description) }}
              {{ form_widget(form.description, {'attr': {'class': 'form-control'}}) }}
            </div>
          <!--  SECOND INSPUT FOR THE ADRESSE-->
            <div class="form-group">
              {{ form_label(form.nbMax, "Nombre de personne max :  ", {'label_attr': {'class': 'control-label'}}) }}
              {{ form_errors(form.nbMax) }}
              {{ form_widget(form.nbMax, {'attr': {'class': 'form-control'}}) }}
            </div>    
           <!--  INSPUT FOR THE TOWN -->
            <div class="form-group">
              {{ form_label(form.equipement, "Equipements", {'label_attr': {'class': 'control-label'}}) }}
              {{ form_errors(form.equipement) }}
              {{ form_widget(form.equipement, {'attr': {'class': 'form-control'}}) }}
            </div>
            
           
             <!--  INSPUT FOR THE ... -->
            <div class="form-group">
              {{ form_label(form.etage, "L'étage ", {'label_attr': {'class': 'control-label'}}) }}
              {{ form_errors(form.etage) }}
              {{ form_widget(form.etage, {'attr': {'class': 'form-control'}}) }}
            </div>  
             <!--  INSPUT FOR THE offices-->
              <div class="form-group">
              {{ form_label(form.superficieReelle, "La superficie réelle", {'label_attr': {'class': 'control-label'}}) }}
              {{ form_errors(form.superficieReelle) }}
              {{ form_widget(form.superficieReelle, {'attr': {'class': 'form-control'}}) }}
            </div> 
             <div class="form-group">
              {{ form_label(form.superficieCommerciale, "La superficie réelle", {'label_attr': {'class': 'control-label'}}) }}
              {{ form_errors(form.superficieCommerciale) }}
              {{ form_widget(form.superficieCommerciale, {'attr': {'class': 'form-control'}}) }}
            </div> 
            <hr> 
             {# Génération automatique des champs pas encore écrits.
             et tous les champs cachés (type « hidden »). #}
             <div id="tarif">
            {{ form_rest(form) }} 
            </div>             
            <!--  VALID BUTTON -->
            <div class="form-group">
              {{ form_widget(form.Valider, {'attr': {'class': 'btn btn-danger btn-lg btn-block'}}) }}
            </div>
                        <hr>
               
            {# Fermeture de la balise <form> du formulaire HTML #}
            {{ form_end(form) }}
            </form>
        </div>
   </div>
 {% endblock %} 

BandCo2.7/path/src/BureauAndCo/SiteBundle/Resources/views/Default/infoSite.html.twig
{% extends '::base.html.twig' %} 
{% block title %}E_Gestion NouveauSite{% endblock %}

{% block body%}
{% if site|length<=0 %}
<div class="surface"> 
  <h4> Aucun site n'est affécté à vous pour le moment.</h4></div>
  {% else %}
  <div class="bloc"> 
    <div class="f">

      <table class="table table-condensed">
       <thead>
        <tr>
          <th>Num</th>
          <th>Nom du Site</th>
          <th>Nombre des bureaux Libres</th>
          <th>Nombre des Salles de réunions Libres</th>
          <th>Nombre des salles de formation Libres</th>

        </tr>
      </thead>
      <tbody>
      
        {% for site in site %}
        <tr>
        <td> {{loop.index}}</td>  
          {% for nb in bureauLibre %}
        
        <td> {{site.nom}}</td>
        
         <td>{{nb}}/{{site.nbBureau}} </td>  
         <td>{{site.nbSalleReunion}}</td> 
         <td>{{site.nbSalleFormation}}</td>
{% endfor %}
        


        <td> <a class="bbtn btn-success btn-xs" href="{{ path('details',{'id':site.id}) }}">Détails </a></td>
        <td>
          <div id="action"><a class="glyphicon glyphicon-edit" href="{{ path('editerSite',{'id':site.id})}}"></a> <a class="glyphicon glyphicon-trash" href="{{ path('confirmSupprimerSite',{'id':site.id})}}"> </a> </div></td>

        </tr>



        
{% endfor %}
      </tbody>
    </table>

  </div>

</div>
{% endif %}
{% endblock %}

BandCo2.7/path/src/BureauAndCo/SiteBundle/Resources/views/Default/listeReservations.html.twig
{% extends '::base.html.twig' %} 
{% block title %}E_Gestion NouveauSite{% endblock %}

{% block body%}
    {% if list|length<=0 %}
    <div class="surface"> 
    <h4> Aucune réservation n'a été trouvée.</h4></div>
    {% else %}
<div class="bloc"> 
<h2>Mes Réservations </h2>
  <div class="f">
    <table class="table table-condensed">
     <thead>
      <tr>
        <th>Num</th>
        <th>Client</th>
        <th>Surface</th>
        <th>Date Début prévue</th>
        <th>Confirmée </th>
        <th>Action</th>

      </tr>
    </thead>
    <tbody>
     {% for reservation in list %}

     <tr>
      <td>{{loop.index}}</td>
      <td> {{reservation.nomClient}}</td>
      <td>{{reservation.surface}}  </td>
      <td>{{reservation.dateDebut|date("d/m/Y à H:m")}}</td>
     
      <td>{{reservation.confirmation}} </td>
       {% if reservation.confirmation=="non" %}
      <td><a href="{{path('confirmerReservation',{'id':reservation.id})}}"> Confirmer </a>-<a href="{{path('supprimerReservation',{'id':reservation.id})}}">supprimer </a></td>
      {% else %}
      <td> <a href="{{path('supprimerReservation',{'id':reservation.id})}}">supprimer </a></td>{% endif %}
      
       
    </tr>
    {% endfor %}
    

  </tbody>
</table>
 <center> <div class="navigation">
    {{ knp_pagination_render(list) }}
</div></center>
</div>

</div>
{% endif %}
{% endblock %}

BandCo2.7/path/src/BureauAndCo/SiteBundle/Resources/views/Default/location.html.twig
{% extends '::base.html.twig' %} 
{% block title %}E_Gestion NouveauSite{% endblock %}

{% block body%}


 <!--  <h2> Nouveau Bureau </h2> -->
 <div class="surface"> 
 <h2> {{title}} : </h2>
 <div class="f">
 <p>{{message}}</p>
    {{ form_start(form, {'attr': {'class': 'form-horizontal'}}) }}
    {# Les erreurs générales du formulaire. #}
    {{ form_errors(form) }}
     <!--  FIRST INSPUT FOR THE OFFICE NUMBER -->
      
                <div class="form-group">
            
               {{ form_label(form.locataire, "Nom du client : ", {'label_attr': {'class': 'control-label'}}) }}
              {{ form_errors(form.locataire) }}
              {{ form_widget(form.locataire, {'attr': {'class': 'form-control'}}) }}
              <div id="nouveauClient"> <a class="bbtn btn-primary btn-xs" id="nouveau" href="{{path('nouveauLocataire')}}">Nouveau client </a></div>
            </div>
            
           
            <div class="form-group"> 
              {{ form_label(form.dateDebut, "Date début : ", {'label_attr': {'class': 'control-label'}}) }}
              {{ form_errors(form.dateDebut) }}
              {{ form_widget(form.dateDebut) }}
            </div>
           <!--  INSPUT FOR THE TOWN -->     
           <hr>
             
            <!--  VALID BUTTON -->
            <div class="form-group">
              {{ form_widget(form.Valider, {'attr': {'class': 'b'}}) }}
            </div>
             <hr>
             {{ form_rest(form)}} 
            {{ form_end(form) }}
            </form>
        </div>

   </div>
 {% endblock %} 
{% block javascripts %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script type="text/javascript" src=" {{ asset('bundles/framework/js/location.js') }} "></script>
{% endblock %}

BandCo2.7/path/src/BureauAndCo/SiteBundle/Resources/views/Default/locations.html.twig
{% extends '::base.html.twig' %} 
{% block title %}E_Gestion NouveauSite{% endblock %}

{% block body%}


 <!--  <h2> Nouveau Bureau </h2> -->
 <div class="surface"> 
 <h2> {{title}} : </h2>
 <div class="f">
 {{message}}
    {{ form_start(form, {'attr': {'class': 'form-horizontal'}}) }}
    {# Les erreurs générales du formulaire. #}
    {{ form_errors(form) }}
     <!--  FIRST INSPUT FOR THE OFFICE NUMBER -->
      
                <div class="form-group">
            
               {{ form_label(form.locataire, "Nom du client : ", {'label_attr': {'class': 'control-label'}}) }}
              {{ form_errors(form.locataire) }}
              {{ form_widget(form.locataire, {'attr': {'class': 'form-control'}}) }}
              <div id="nouveauClient"> <a class="bbtn btn-primary btn-xs" id="nouveau" href="{{path('nouveauLocataire')}}">Nouveau client </a></div>
            </div>
             <div class="form-group">

              {{ form_label(form.site, "Site  : ", {'label_attr': {'class': 'control-label'}}) }}
              {{ form_errors(form.site) }}
              {{ form_widget(form.site, {'attr': {'class': 'site'}}) }}
            </div>
            <div class="form-group">

              {{ form_label(form.surface, "Surfaces libres dans le site choisi : ", {'label_attr': {'class': 'control-label'}}) }}
              {{ form_errors(form.surface) }}
              {{ form_widget(form.surface, {'attr': {'class': 's'}}) }}
            </div>
            <div class="form-group"> 
              {{ form_label(form.dateDebut, "Date début : ", {'label_attr': {'class': 'control-label'}}) }}
              {{ form_errors(form.dateDebut) }}
              {{ form_widget(form.dateDebut) }}
            </div>
           <!--  INSPUT FOR THE TOWN -->     
           <hr>
             
            <!--  VALID BUTTON -->
            <div class="form-group">
              {{ form_widget(form.Valider, {'attr': {'class': 'b'}}) }}
            </div>
             <hr>
             {{ form_rest(form)}} 
            {{ form_end(form) }}
            </form>
        </div>

   </div>
 {% endblock %} 
{% block javascripts %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script type="text/javascript" src=" {{ asset('bundles/framework/js/location.js') }} "></script>
<script src="{{ asset('bundles/fosjsrouting/js/router.js') }}"></script>
<script src="{{ path('fos_js_routing_js', { callback: 'fos.Router.setData' }) }}"></script>
{% endblock %}

BandCo2.7/path/src/BureauAndCo/SiteBundle/Resources/views/Default/nouveauEnfant.html.twig
{% extends '::base.html.twig' %} 
{% block title %}E_Gestion NouveauSite{% endblock %}

{% block body%}


 <!--  <h2> Nouveau Bureau </h2> -->
 <div class="surface"> 
 <h2>{{title}}</h2>
 <div class="f">
  <p>{{message}}</p>
 
    {{ form_start(form, {'attr': {'class': 'form-horizontal'}}) }}
    {# Les erreurs générales du formulaire. #}
    {{ form_errors(form) }}
     <!--  FIRST INSPUT FOR THE OFFICE NUMBER -->
            
             <div class="form-group">
            
              {{ form_label(form.parent, "Le parent : ", {'label_attr': {'class': 'control-label'}}) }}
              {{ form_errors(form.parent) }}
              {{ form_widget(form.parent, {'attr': {'class': 'form-control'}}) }}
            </div>
            <div class="form-group">

              {{ form_label(form.num, "Numéro de l'enfant : ", {'label_attr': {'class': 'control-label'}}) }}
              {{ form_errors(form.num) }}
              {{ form_widget(form.num, {'attr': {'class': 'form-control'}}) }}
            </div>
          <!--  SECOND INSPUT FOR THE ADRESSE-->
            <div class="form-group">
              {{ form_label(form.nbMax, "Nombre de place :  ", {'label_attr': {'class': 'control-label'}}) }}
              {{ form_errors(form.nbMax) }}
              {{ form_widget(form.nbMax, {'attr': {'class': 'form-control'}}) }}
            </div>    
           <!--  INSPUT FOR THE TOWN -->
            <div class="form-group">
              {{ form_label(form.equipement, "Equipements", {'label_attr': {'class': 'control-label'}}) }}
              {{ form_errors(form.equipement) }}
              {{ form_widget(form.equipement, {'attr': {'class': 'form-control'}}) }}
            </div>
               <!--  INSPUT FOR THE COUNTRY -->
           
             <!--  INSPUT FOR THE ... -->
            <div class="form-group">
              {{ form_label(form.etage, "L'étage ", {'label_attr': {'class': 'control-label'}}) }}
              {{ form_errors(form.etage) }}
              {{ form_widget(form.etage, {'attr': {'class': 'form-control'}}) }}
            </div>  
             <!--  INSPUT FOR THE offices-->
              <div class="form-group">
              {{ form_label(form.superficieReelle, "La superficie réelle : ", {'label_attr': {'class': 'control-label'}}) }}
              {{ form_errors(form.superficieReelle) }}
              {{ form_widget(form.superficieReelle, {'attr': {'class': 'form-control'}}) }}
            </div>  
             <div class="form-group">
              {{ form_label(form.superficieCommerciale, "La superficie commerciale : ", {'label_attr': {'class': 'control-label'}}) }}
              {{ form_errors(form.superficieCommerciale) }}
              {{ form_widget(form.superficieCommerciale, {'attr': {'class': 'form-control'}}) }}
            </div> 
              <div id="tarif">
              {{ form_rest(form)}} 
             </div>
               
            <!--  VALID BUTTON -->
            <div class="form-group">
              {{ form_widget(form.Valider, {'attr': {'class': 'btn btn-danger btn-lg btn-block'}}) }}
            </div>
             <hr>
            {{ form_end(form) }}
            </form>
        </div>

   </div>
 {% endblock %} 